#dubbo:
#  application:
#    name: pro
#  protocols:
#    p1:
#      name: rest
#      port: 20881
#    p2:
#      name: dubbo
#      port: 20880
#  registry:
#    address: zookeeper://127.0.0.1:2181
#    timeout: 25000